name: ESLint

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:

  eslint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: latest

      - run: npm install
      - run: npm run eslint